name: deploy main
on:
  push:
    branches:
      - main

env:
  TZ: "Asia/Tokyo"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy with vercel
        run: |
          mkdir .vercel
          echo {\"orgId\": \"${{ secrets.VERCEL_ORG_ID }}\", \"projectId\": \"${{ secrets.VERCEL_PROJECT_ID }}\"} > .vercel/project.json
          npx vercel --token ${{secrets.VERCEL_TOKEN}} --prod
